version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - inception_network

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    expose:
      - "9000"
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/html/wordpress
    networks:
      - inception_network

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/html/wordpress
    networks:
      - inception_network

volumes:
  wp_volume:
    driver: local
    driver_opts:
      type: volume
      # device: /Users/sanghan/han/hangit/inception
      device: /home/sanghan/data/wordpress
      o: bind

  db_volume:
    driver: local
    driver_opts:
      type: volume
      # device: /Users/sanghan/han/hangit/inception/srcs/requirements/tools/mariadb
      device: /home/sanghan/data/mariadb
      o: bind

networks:
  inception_network:
    driver: bridge
