version: '3'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PASSWORD: example

  nginx:
    depends_on:
      - wordpress
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
